#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index
news:
  path: /articles
  controller: App\Controller\ArticleController:index
entrainement:
  path: /entrainements
  controller: App\Controller\EntrainementController::index
competition:
  path: /competitions
  controller: App\Controller\CompetitionController::index
club:
  path: /club
  controller: App\Controller\ClubController::index
login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST
registration:
  path: /inscription
  controller: App\Controller\SecurityController::registration
  methods: GET|POST
logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
profile:
  path: /profil
  controller: App\Controller\ProfileController::index
admin_home:
  path: /admin
  controller: App\Controller\AdminController::home
admin_articles:
  path: /admin/articles
  controller: App\Controller\AdminController::articles
admin_entrainements:
  path: /admin/entrainements
  controller: App\Controller\AdminController::entrainements
admin_users:
  path: /admin/utilisateurs
  controller: App\Controller\AdminController::users
admin_users_edit:
  path: /admin/utilisateurs/{id}/edit
  controller: App\Controller\AdminController::editUser
app_verify_email:
  path: /verify_email
  controller: App\Controller\SecurityController::verifyUserEmail